version: '3'

services:
  transfer_db:
    environment:
      - SOURCE_DB_HOST
      - SOURCE_DB_PORT
      - SOURCE_DB_USER
      - SOURCE_DB_PASSWORD
      - SOURCE_DB_NAME
      - TARGET_DB_HOST
      - TARGET_DB_PORT
      - TARGET_DB_USER
      - TARGET_DB_PASSWORD
      - TARGET_DB_NAME
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: transfer_db
